dataset:
  note_duration: [3.0, 1.0]
  n_fft: 1024
  fft_hop: 256
  midi_notes: [[60, 85]]
  multichannel_stacked_spectrograms: False
  n_mel_bins: 257
  spectrogram_min_dB: -120.0
  algos: null
  operators: [1, 2, 3, 4, 5, 6]
  vst_params_learned_as_categorical: all<=32
  restrict_to_labels: null
  dataset_dir: /dataset/preset-gen-vae/numcatpp

train:
  current_k_fold: 0
  k_folds: 5
  test_holdout_proportion: 0.2
  minibatch_size: 32
  optimizer: Adam
  start_epoch: 0
  n_epochs: 400
  save_period: 20
  plot_period: 20
  weight_decay: 0.0001
  fc_dropout: 0.3
  reg_fc_dropout: 0.4
  normalize_losses: True
  latent_loss: Dkl
  params_cat_bceloss: False
  params_cat_softmax_temperature: 0.2
  latent_flow_input_regularization: bn
  initial_learning_rate: 0.0002
  lr_warmup_start_factor: 0.1
  lr_warmup_epochs: 6
  beta: 0.2 
  beta_start_value: 0.1
  beta_warmup_epochs: 25
  adam_betas: [0.9, 0.999]
  scheduler_name: ReduceLROnPlateau
  scheduler_loss: [ReconsLoss/Backprop, Controls/BackpropLoss]
  scheduler_lr_factor: 0.2
  scheduler_patience: 6
  scheduler_cooldown: 6
  scheduler_threshold: 0.0001
  contrastive_coef: 0.1
  early_stop_lr_threshold: 0
  logged_samples_count: 4
  

model:
  name: vit_FlReg
  run_name: kfold0-s1
  input_type: spectrogram
  stack_spectrograms: False
  stack_specs_deepest_features_mix: False
  concat_midi_to_z: False
  sampling_rate: 22050
  waveform_size: 88576
  spectrogram_size: [257, 347]
  input_tensor_size: null
  dim_z: 612
  params_reg_softmax: False
  params_regression_architecture: flow_realnvp_6l300 # mlp_4l1024 / flow_realnvp_6l300
  latent_flow_arch: null # realnvp_6l300, null
  forward_controls_loss: True
  stochastic_latent: False
  latent_quantization: null
  encoder_architecture: audiomae # speccnn8l1_bn / audiomae
  decoder_architecture: null # speccnn8l1_bn / null
  contrastive: False
  pretrained_dir: /exp_logs/preset-gen-vae/audiomae/default/checkpoint-300.pth


verbosity: 1
synth_params_count: -1
learnable_params_tensor_length: -1
logs_root_dir: /exp_logs/preset-gen-vae
allow_erase_run: True
main_cuda_device_idx: 0




