model:
  encoder_kwargs:
    backbone: PatchEmbed # CNNBackbone / PatchEmbed
    tr_encoder: CSWinTransformer # TransformerEncoder / CSWinTransformer
    d_model: 512
    n_queries: 144
    backbone_kwargs:
      out_dim: 64 # d_model//8 for CSWin
      spectrogram_channels: 1
      kernel_size: # for PatchEmbed
        - 7
        - 7
      stride: # for PatchEmbed
        - 4
        - 6
      padding: # for PatchEmbed
        - 2
        - 2
      norm: layernorm # batchnorm / layernorm
    transformer_kwargs:
      nhead: 8 
      num_encoder_layers: [1, 2, 21, 1] # 6 / [1, 2, 2, 1]
      num_decoder_layers: 6
      dim_feedforward: 1024
      dropout: 0.1
      activation: gelu
      normalize_before: True
      