logs_root_dir: /data2/personal/swc/exp_logs/preset-gen-vae
verbosity: 1
allow_erase_run: False

train:
  dataset: surge
  expl_epoch: 0
  start_epoch: 381
  n_epochs: 401
  save_period: 10
  eval_period: 10

model:
  name: dexed_normalized_newmel_cos
  run_name: kfold0-s3-rere
  saved_path: dexed_normalized_newmel_cos/kfold0-s3-re

optim:
  initial_lr: 0.00002
  weight_decay: 0.0001
  betas: [0.9, 0.999]

scheduler:
  gamma: 0.99 # 0.99
  warmup_epochs: 10 # 10, -1
  warmup_start_factor: 0.2 # 0.2
  load: False

loss:
  param: False
  normalize_losses: True
  cat_softmax_t: 0.2
  label_smoothing: True
  per: True
  pg: True
  audio_eval_n_workers: 16
  pg_logp_threshold: 0
  pg_coef:
    s_value: 0.0
    e_value: 1.0
    s_epoch: 199
    e_epoch: 299