logs_root_dir: /data2/personal/swc/exp_logs/preset-gen-vae
verbosity: 1
allow_erase_run: False

train:
  dataset: surge
  expl_epoch: 1
  start_epoch: 399
  n_epochs: 1000
  save_period: 50
  eval_period: 1

model:
  name: buffer_logtest_0_sc_p5_x10
  run_name: kfold0-s1
  saved_path: dexed_normalized_newmel-rl_p5-lr_new/kfold0-s1

optim:
  initial_lr: 0.00002
  weight_decay: 0.0001
  betas: [0.9, 0.999]

scheduler:
  gamma: 0.99 # 0.99
  warmup_epochs: 10 # 10
  warmup_start_factor: 0.2 # 0.2
  load: False

loss:
  param: False
  normalize_losses: True
  cat_softmax_t: 0.2
  label_smoothing: True
  pg: True
  audio_eval_n_workers: 16
  pg_logp_threshold: 0
  pg_coef:
    s_value: 0.0
    e_value: 1.0
    s_epoch: 200
    e_epoch: 300